E-commerce Customer Orders

In [1]:
import pandas as pd

In [41]:
customers = {
    "CustomerID": [101, 102, 103, 104, 105],
    "Name": ["Ravi Kumar", "Sita Reddy", "Manoj Singh", "Priya Sharma", "Arjun Das"],
    "City": ["Hyderabad", "Chennai", "Bangalore", "Mumbai", "Delhi"],
    "Segment": ["Retail", "Corporate", "Retail", "Home Office", "Corporate"]
}

orders = {
    "OrderID": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008],
    "CustomerID": [101, 102, 103, 101, 104, 105, 102, 103],
    "OrderDate": pd.date_range(start="2025-08-01", periods=8, freq="D"),
    "Product": ["Laptop", "Phone", "Tablet", "Headphones", "Monitor", "Laptop", "Phone", "Printer"],
    "Quantity": [1, 2, 1, 3, 2, 1, 1, 2],
    "Price": [70000, 25000, 15000, 3000, 12000, 72000, 26000, 15000]
}

df = pd.DataFrame(customers)
print(df)
print()
print()
df_orders = pd.DataFrame(orders)
df_orders["Revenue"] = df_orders["Quantity"] * df_orders["Price"]
print(df_orders)

merge = df.merge(df_orders)
print(merge)
print()
print()
vc = df.value_counts()
print(vc)

print("----")

most_orders = df_orders["CustomerID"].value_counts().reset_index()

print(most_orders)
# Group by customer and calculate total revenue
customer_revenue = df_orders.groupby("CustomerID")["Revenue"].sum().reset_index()

# Sort by revenue in descending order
top_customer = customer_revenue.sort_values(by="Revenue", ascending=False).head(1)

print("Top Revenue Customer:")
print(top_customer)


# revenue_by_customer = df_orders.groupby("CustomerID")["Revenue"].sum().reset_index()
# revenue_by_customer.columns = ["c_id","rev"]
# print(revenue_by_customer)  
# print()
# print()

# top_re = df.loc[df["Name"]["Revenue"].idxmax()]
# print(top_re)

   CustomerID          Name       City      Segment
0         101    Ravi Kumar  Hyderabad       Retail
1         102    Sita Reddy    Chennai    Corporate
2         103   Manoj Singh  Bangalore       Retail
3         104  Priya Sharma     Mumbai  Home Office
4         105     Arjun Das      Delhi    Corporate


   OrderID  CustomerID  OrderDate     Product  Quantity  Price  Revenue
0     1001         101 2025-08-01      Laptop         1  70000    70000
1     1002         102 2025-08-02       Phone         2  25000    50000
2     1003         103 2025-08-03      Tablet         1  15000    15000
3     1004         101 2025-08-04  Headphones         3   3000     9000
4     1005         104 2025-08-05     Monitor         2  12000    24000
5     1006         105 2025-08-06      Laptop         1  72000    72000
6     1007         102 2025-08-07       Phone         1  26000    26000
7     1008         103 2025-08-08     Printer         2  15000    30000
   CustomerID          Name       City      Segment  OrderID  OrderDate  \
0         101    Ravi Kumar  Hyderabad       Retail     1001 2025-08-01
1         101    Ravi Kumar  Hyderabad       Retail     1004 2025-08-04
2         102    Sita Reddy    Chennai    Corporate     1002 2025-08-02
3         102    Sita Reddy    Chennai    Corporate     1007 2025-08-07
4         103   Manoj Singh  Bangalore       Retail     1003 2025-08-03
5         103   Manoj Singh  Bangalore       Retail     1008 2025-08-08
6         104  Priya Sharma     Mumbai  Home Office     1005 2025-08-05
7         105     Arjun Das      Delhi    Corporate     1006 2025-08-06

      Product  Quantity  Price  Revenue
0      Laptop         1  70000    70000
1  Headphones         3   3000     9000
2       Phone         2  25000    50000
3       Phone         1  26000    26000
4      Tablet         1  15000    15000
5     Printer         2  15000    30000
6     Monitor         2  12000    24000
7      Laptop         1  72000    72000


CustomerID  Name          City       Segment
101         Ravi Kumar    Hyderabad  Retail         1
102         Sita Reddy    Chennai    Corporate      1
103         Manoj Singh   Bangalore  Retail         1
104         Priya Sharma  Mumbai     Home Office    1
105         Arjun Das     Delhi      Corporate      1
Name: count, dtype: int64
----
   CustomerID  count
0         101      2
1         102      2
2         103      2
3         104      1
4         105      1
Top Revenue Customer:
   CustomerID  Revenue
0         101    79000